# style_category: liquidity
factor_definition:
- name: amount
  style_category: liquidity
  action: null
  time_alignment: shift
  description: 每日成交额，用于计算流动性指标。
- name: turnover_rate
  style_category: liquidity
  action: null
  time_alignment: shift
  description: 每日换手率。
- name: turnover_42d_std_252d_std_ratio
  style_category: liquidity
  description: ''
  action: technical_calcu
  time_alignment: shift
- name: turnover_rate_monthly_mean
  style_category: liquidity
  description: 月平均换手率，衡量股票在一段时间内的交易活跃度。
  action: technical_calcu
  time_alignment: shift
- name: turnover_rate_90d_mean
  style_category: liquidity
  description: 90日（约一季度）平均换手率，比单日或月度指标更能平滑地衡量股票的交易活跃度。
  action: technical_calcu
  time_alignment: shift
- name: ln_turnover_value_90d
  style_category: liquidity
  description: 90日日均成交额的对数。反映了资产的绝对流动性水平，是冲击成本的重要代理变量。建议取对数。
  action: technical_calcu
  time_alignment: shift
- name: turnover_t1_div_t20d_avg
  style_category: liquidity
  description: 成交额突然放大，往往伴随趋势/事件驱动。。
  action: technical_calcu
  time_alignment: shift
- name: amihud_liquidity
  style_category: liquidity
  description: Amihud非流动性指标，衡量单位成交额能引起多大的价格波动，是冲击成本的优秀代理变量。
  action: technical_calcu
  time_alignment: shift
