# style_category: momentum
factor_definition:
- name: rstr_m6
  style_category: momentum
  description: ''
  action: technical_calcu
  time_alignment: shift
- name: momentum_1d
  style_category: momentum
  description: ''
  action: technical_calcu
  time_alignment: shift
- name: momentum_5d
  style_category: momentum
  description: ''
  action: technical_calcu
  time_alignment: shift
- name: sharpe_momentum_60d
  style_category: momentum
  description: 传统的动量因子只关心收益率，但高收益可能伴随着高风险。夏普动量通过用波动率 来调整历史收益率，旨在寻找那些“稳定上涨”的股票，剔除纯粹因高波动而产生 高收益的股票，信号质量通常更高
  action: technical_calcu
  time_alignment: shift
- name: momentum_12_1
  style_category: momentum
  description: 过去12个月剔除最近1个月的累计收益率，最经典的截面动量因子，捕捉中期价格惯性。
  action: technical_calcu
  time_alignment: shift
- name: momentum_12_2
  style_category: momentum
  description: 过去12个月剔除最近2个月的累计收益率，最经典的截面动量因子，捕捉中期价格惯性。
  action: technical_calcu
  time_alignment: shift
- name: momentum_20d
  style_category: momentum
  description: 20日动量/收益率，捕捉短期趋势，常用于高频一些的策略。
  action: technical_calcu
  time_alignment: shift
- name: momentum_pct_60d
  style_category: momentum
  description: 捕捉中期价格惯性。
  action: technical_calcu
  time_alignment: shift
- name: momentum_120d
  style_category: momentum
  description: 120日（约半年）累计收益率，捕捉中期价格惯性。
  action: technical_calcu
  time_alignment: shift
- name: reversal_21d
  style_category: momentum
  description: 21日（约1个月）收益率的负向。A股短期反转效应显著，即前期涨多的股票后期倾向于跌。
  action: technical_calcu
  time_alignment: shift
- name: reversal_5d
  style_category: momentum
  description: 周 收益率的负向。A股短期反转效应显著，即前期涨多的股票后期倾向于跌。
  action: technical_calcu
  time_alignment: shift
- name: quality_momentum
  style_category: momentum
  description: 高质量动量。风险调整后的动量因子(120日动量 / 90日波动率)，作为“分析师评级上调”的代理，旨在寻找稳步上涨的股票。
  action: technical_calcu
  time_alignment: shift
